** TODO wizard per ricerca soggetti? Si sceglie all'inizio se persona fisica o giuridica, e compaiono i campi appropriati
** TODO modalità visualizzazione risultati ricerca per persona. Tabella che mescola persone e sinistri? Oppure reingegnerizzazione?
** TODO nella maschera dettagli sinistro, i dati relativi alle persone sono specifici del singolo sinistro? 
   Se mostrassimo un piccolo grafico nella tabella, in modo da evidenziare i veicoli sospetti?
** TODO query estrazione dati sinistri, veicoli e soggetti (codice BDS)



consultazione batch e online
quante chiavi di ricerca non sono presenti nei dati delle imprese?
codice sinistro -> non ci sono controlli, non viene usato come campo di ricerca
aggreagazioni per compagnia, userid sinistro date

verificare se infrastruttura banca gestisce sessioni multiple dello stesso utente (forze ordine)


white black list

bl : dato errato


CRUD classic su black list
su white : su portale tabella da arricchire per informarci su cambio partita iva e altro


bl codice sìfiscale o targa

wl flag su soggetti e targhe

lista in excel e aggiorna in update white 
sempre insert in black

update massivo con foglio excel, modifica e cancellazione puntuale
cancellazione con checkbox massiva

stessa cosa con black list
con auditing su chi ha modificato le liste

compagnia può dare informazioni su codice fiscale, partita iva e messaggio testo naturale

detection white list?

maschera di Maria su risultati interrogazione sinistri


piattaforma: vincoli su chi può leggere documento caricato: solo compagnie interessate nel sinistro possono accedere alla documentazione
