(defaction (target ((pose pose)))
    (to-list () `(target :pose ,pose :pre ,(synth to-list pre) :post ,(synth to-list post)))
  ;; (to-req () (hcat (text "effettua una transizione verso ") (synth to-url pose)))
  (to-html () (multitags (text "effettua una transizione verso il seguente URL:") 
                         (code nil (synth to-url pose))
                         (dlist pre (text "Precondizione: ") (synth to-html pre)
                                post (text "Postcondizione:") (synth to-html post)))))
