(defaction (target ((pose pose)))
    (to-list () `(target :pose ,pose :pre ,(synth to-list pre) :post ,(synth to-list post)))
  ;; (to-req () (hcat (text "effettua una transizione verso ") (synth to-url pose)))
  (to-html () (span nil (text "effettua una transizione verso il seguente URL:") 
                    (code nil (synth to-url pose))
                    (dlist pre (span nil (text "Precondizione: ")) (synth to-html pre)
                           post (span nil (text "Postcondizione:")) (synth to-html post)))))
