(defaction (translate ((source filter)
                            (target variable)
                            (result variable)))
  (to-list () `(translate (:source  ,(synth to-list source) :target ,(synth to-list target) :result ,(synth to-list result) :pre ,(synth to-list pre) :post ,(synth to-list post))))
  (to-html () (div nil 
		   (text "Sia ") 
		   (synth to-html result) 
		   (text " il risultato della compilazione del seguente sorgente:")
		   (div (list :class 'well) (synth to-req source))
                   (maybes (list pre (span nil (text "Precondizione:")))
                           (list post (span nil (text "Postcondizione:")))))))

(defun translate2 (source &key pre post)
  (let ((result (variab (gensym))))
    (values (translate source nil result :pre pre :post post) result)))
