(load "d:/giusv/lisp/extent/lol.lisp")
(load "d:/giusv/lisp/extent/utils.lisp")
(load "d:/giusv/lisp/extent/parser.lisp")
(load "d:/giusv/lisp/extent/grammar.lisp")
(load "d:/giusv/lisp/extent/doc.lisp")
(load "d:/giusv/lisp/extent/xml.lisp")
(load "d:/giusv/lisp/extent/html.lisp")
(load "d:/giusv/lisp/extent/documentation.lisp")
(load "d:/giusv/lisp/extent/expression.lisp")
(load "d:/giusv/lisp/extent/url.lisp")
(load "d:/giusv/lisp/extent/rbac.lisp")

(load "d:/giusv/lisp/extent/data.lisp")
(load "d:/giusv/lisp/extent/data/json.lisp")
(load "d:/giusv/lisp/extent/data/entity.lisp")
(load "d:/giusv/lisp/extent/data/jsonschema.lisp")

(load "d:/giusv/lisp/extent/query.lisp")

(load "d:/giusv/lisp/extent/action.lisp")
(load "d:/giusv/lisp/extent/action/rest.lisp")
(load "d:/giusv/lisp/extent/action/translate.lisp")
(load "d:/giusv/lisp/extent/action/persistence.lisp")
(load "d:/giusv/lisp/extent/action/conversion.lisp")
(load "d:/giusv/lisp/extent/action/target.lisp")
(load "d:/giusv/lisp/extent/action/extraction.lisp")
;; (load "d:/giusv/lisp/extent/action/validate.lisp")

(load "d:/giusv/lisp/extent/process.lisp")
(load "d:/giusv/lisp/extent/service.lisp")
(load "d:/giusv/lisp/extent/application.lisp")
(load "d:/giusv/lisp/extent/database.lisp")

(load "d:/giusv/lisp/extent/gui/button.lisp")
(load "d:/giusv/lisp/extent/gui/checkbox.lisp")
(load "d:/giusv/lisp/extent/gui/input.lisp")
(load "d:/giusv/lisp/extent/gui/textarea.lisp")
(load "d:/giusv/lisp/extent/gui/label.lisp")
(load "d:/giusv/lisp/extent/gui/horz.lisp")
(load "d:/giusv/lisp/extent/gui/vert.lisp")
(load "d:/giusv/lisp/extent/gui/alt.lisp")
(load "d:/giusv/lisp/extent/gui/abst.lisp")
(load "d:/giusv/lisp/extent/gui/static.lisp")
(load "d:/giusv/lisp/extent/gui/dynamic.lisp")
(load "d:/giusv/lisp/extent/gui/tabular.lisp")
(load "d:/giusv/lisp/extent/gui/pivot.lisp")
(load "d:/giusv/lisp/extent/gui/chart.lisp")
(load "d:/giusv/lisp/extent/gui/description.lisp")
(load "d:/giusv/lisp/extent/gui/listing.lisp")
(load "d:/giusv/lisp/extent/gui/form.lisp")
(load "d:/giusv/lisp/extent/gui/anchor.lisp")
(load "d:/giusv/lisp/extent/gui/navbar.lisp")
(load "d:/giusv/lisp/extent/gui/panel.lisp")
(load "d:/giusv/lisp/extent/gui/conditional.lisp")
(load "d:/giusv/lisp/extent/gui/modal.lisp")
(load "d:/giusv/lisp/extent/gui.lisp")

(load "d:/giusv/lisp/extent/aia/dataformats.lisp")
(load "d:/giusv/lisp/extent/aia/roles.lisp")

(load "d:/giusv/lisp/extent/aia/console/indicators.lisp")
(load "d:/giusv/lisp/extent/aia/console/companies.lisp")
(load "d:/giusv/lisp/extent/aia/console/news.lisp")

(load "d:/giusv/lisp/extent/aia/console/authmanage.lisp") 
(load "d:/giusv/lisp/extent/aia/console/inquiryaudit.lisp") 
(load "d:/giusv/lisp/extent/aia/console/platformaudit.lisp") 
(load "d:/giusv/lisp/extent/aia/console/white.lisp")
(load "d:/giusv/lisp/extent/aia/console/black.lisp")
(load "d:/giusv/lisp/extent/aia/console/blackwhite.lisp")

(load "d:/giusv/lisp/extent/aia/console/console.lisp")

(load "d:/giusv/lisp/extent/aia/server/companycrud.lisp")
(load "d:/giusv/lisp/extent/aia/server/newscrud.lisp")
(load "d:/giusv/lisp/extent/aia/server/indicatorcrud.lisp")
(load "d:/giusv/lisp/extent/aia/server/documentcrud.lisp")
(load "d:/giusv/lisp/extent/aia/server/blackcrud.lisp")
(load "d:/giusv/lisp/extent/aia/server/whitecrud.lisp")
;; (load "d:/giusv/lisp/extent/aia/server/platform.lisp")
(load "d:/giusv/lisp/extent/aia/server/inquiry.lisp")
(load "d:/giusv/lisp/extent/aia/server/aia.lisp")


(load "d:/giusv/lisp/extent/aia/website/plate.lisp")
(load "d:/giusv/lisp/extent/aia/website/person.lisp")
(load "d:/giusv/lisp/extent/aia/website/document.lisp")
(load "d:/giusv/lisp/extent/aia/website/website.lisp")

(load "d:/giusv/lisp/extent/aia/main.lisp")


