;; (defparameter *prj-home* "d:/lisp/extent/")

(load "d:/giusv/lisp/extent/utils.lisp")
(load "d:/giusv/lisp/extent/parser.lisp")
(load "d:/giusv/lisp/extent/grammar.lisp")
(load "d:/giusv/lisp/extent/expression.lisp")
(load "d:/giusv/lisp/extent/doc.lisp")
(load "d:/giusv/lisp/extent/url.lisp")
(load "d:/giusv/lisp/extent/json.lisp")
(load "d:/giusv/lisp/extent/entity.lisp")
(load "d:/giusv/lisp/extent/query.lisp")
(load "d:/giusv/lisp/extent/process.lisp")
(load "d:/giusv/lisp/extent/jsonschema.lisp")
(load "d:/giusv/lisp/extent/xml.lisp")
(load "d:/giusv/lisp/extent/html.lisp")
(load "d:/giusv/lisp/extent/form.lisp")
(load "d:/giusv/lisp/extent/gui.lisp")
