(load "d:/giusv/lisp/extent/utils.lisp")
(load "d:/giusv/lisp/extent/parser.lisp")
(load "d:/giusv/lisp/extent/grammar.lisp")
(load "d:/giusv/lisp/extent/doc.lisp")
(load "d:/giusv/lisp/extent/xml.lisp")
(load "d:/giusv/lisp/extent/html.lisp")
(load "d:/giusv/lisp/extent/documentation.lisp")
(load "d:/giusv/lisp/extent/expression.lisp")
(load "d:/giusv/lisp/extent/url.lisp")

(load "d:/giusv/lisp/extent/data.lisp")
(load "d:/giusv/lisp/extent/data/json.lisp")
(load "d:/giusv/lisp/extent/data/entity.lisp")
(load "d:/giusv/lisp/extent/data/jsonschema.lisp")

;; (load "d:/giusv/lisp/extent/query.lisp")

(load "d:/giusv/lisp/extent/action.lisp")
(load "d:/giusv/lisp/extent/action/rest.lisp")
(load "d:/giusv/lisp/extent/action/translate.lisp")
(load "d:/giusv/lisp/extent/action/persistence.lisp")
(load "d:/giusv/lisp/extent/action/target.lisp")
(load "d:/giusv/lisp/extent/action/extraction.lisp")
(load "d:/giusv/lisp/extent/action/validate.lisp")

(load "d:/giusv/lisp/extent/process.lisp")
(load "d:/giusv/lisp/extent/service.lisp")


(load "d:/giusv/lisp/extent/gui/button.lisp")
(load "d:/giusv/lisp/extent/gui/input.lisp")
(load "d:/giusv/lisp/extent/gui/textarea.lisp")
(load "d:/giusv/lisp/extent/gui/label.lisp")
(load "d:/giusv/lisp/extent/gui/horz.lisp")
(load "d:/giusv/lisp/extent/gui/vert.lisp")
(load "d:/giusv/lisp/extent/gui/alt.lisp")
(load "d:/giusv/lisp/extent/gui/abst.lisp")
(load "d:/giusv/lisp/extent/gui/static.lisp")
(load "d:/giusv/lisp/extent/gui/dynamic.lisp")
(load "d:/giusv/lisp/extent/gui/tabular.lisp")
(load "d:/giusv/lisp/extent/gui/form.lisp")
(load "d:/giusv/lisp/extent/gui/anchor.lisp")
(load "d:/giusv/lisp/extent/gui/navbar.lisp")
(load "d:/giusv/lisp/extent/gui/panel.lisp")
(load "d:/giusv/lisp/extent/gui.lisp")


(load "d:/giusv/lisp/extent/aia/dataformats.lisp")
(load "d:/giusv/lisp/extent/aia/console/indicators2.lisp")
(load "d:/giusv/lisp/extent/aia/console/companies.lisp")
(load "d:/giusv/lisp/extent/aia/console/news.lisp")
;; (load "d:/giusv/lisp/extent/aia/console/console.lisp")
(load "d:/giusv/lisp/extent/aia/server/companycrud.lisp")
;; (load "d:/giusv/lisp/extent/aia/console.lisp")


