(defun option-panel (label target)
  (panel (label (const label))
	 (anchor (gensym) (const "Vai alla pagina") :click (target target))))
(defmacro defelement (name elem)
  `(defparameter ,name ,elem))

(defmacro hub-spoke (triples base layout)
  `(let* ,(mapcar #'(lambda (triple)
		      (let ((name (first triple))
			    (label (second triple)))
			`(,name (option-panel ,label ,(url `(,base / ,name))))))
		  triples)
     (alt ,layout ,@(mapcar #'(lambda (triple) 
			(let ((name (first triple))
			      (elem (third triple)))
			  `(static2 ,(keyw name) nil ,elem)))
		    triples))))