(defprod element (anchor ((name symbol) (expr expression)
			  &key (click (click process)) (hover (hover process))))
  (to-list () `(anchor (:name ,name :expr ,(synth to-list expr) 
			    :click ,(synth to-list click)
			    :hover ,(synth to-list hover))))
  ;; (to-req (path) (vcat (hcat (text "Link identificato come ~a e etichettato con la seguente espressione:" (lower name)) 
  ;;       		     (synth to-req expr))
  ;;       	       (nest 4 (hcat (text "Sottoposto a click, ") (synth to-req click)))
  ;;       	       (synth to-req hover)))
  (to-html (path) (div nil 
		       (div nil (text "Link identificato come ~a e etichettato con la seguente espressione:" (lower name)) 
			    (synth to-html expr))
                       (dlist click (span nil (text "Sottoposto a click: ")) (synth to-html click)
                              hover (span nil (text "Sottoposto a hover: ")) (synth to-html hover)))))

(defmacro anchor* (expr &key click hover)
  `(anchor (gensym "ANCHOR") ,expr :click ,click :hover ,hover))
