(defprod element (button ((id string) (expr expression)
			  &key (click (click process)) (hover (hover process))))
  (to-list () `(button (:id ,id :expr ,(synth to-list expr) 
			    :click ,(synth to-list click)
			    :hover ,(synth to-list hover))))
  (to-req (path) (vcat (hcat (text "Pulsante identificato come ~a e etichettato con la seguente espressione:" (lower id)) 
			     (synth to-req expr))
		       (nest 4 (hcat (text "Sottoposto a click, ") (synth to-req click)))
		       (synth to-req hover)))
  (to-html (path) (div (list :class 'well) 
		       (div nil (text "Pulsante identificato come ~a e etichettato con la seguente espressione:" (lower id)) 
			    (synth to-html expr))
		       (if click (div nil (text "Sottoposto a click, ") (synth to-html click)))
		       (if hover (div nil (text "Sottoposto a hover, ") (synth to-html hover))))))