(defprod element (checkbox ((name symbol) 
                            &key (init (init expression)) 
                            (click (click process))))
  (to-list () `(checkbox (:name ,name :init ,(synth to-list init) 
                                :click ,(synth to-list click))))
  (to-html (path) (multitags 
                   (text "Checkbox identificata come")
                   (strong nil (text "~a" (lower name)))
                   (dlist init (span nil (text "Valore iniziale")) (synth to-html init)
                          click (span nil (text "Sottoposto a click: ")) (synth to-html click))))
  (to-brief (path) (synth to-html (checkbox name expr :init init :click click) path)) 
  (req (path) nil))

(defmacro checkbox* (&key init click)
  `(checkbox (gensym "CHECKBOX") :init ,init :click ,click))
