(defprod element (conditional ((name symbol)
                               (expr expression)
                               (true element)))
  (to-list () `(conditional (:name ,name :expr ,(synth to-list expr) :true ,(synth to-list true))))
  (to-html (path) (multitags (text "Elemento condizionale identificato come ")
                             (span-color (lower-camel name))
                             (text " guidato dall'espressione seguente:")
                             (synth to-html expr)
                             (dlist true (span nil (text "Vero")) (synth to-html true path))))
  (to-brief (path) (synth to-html (conditional name expr true) path))
  (to-model () (synth to-model true))
  (toplevel () nil)
  (req (path) (synth req true)))
 
(defmacro conditional* (expr true)
  `(conditional (gensym "CONDITIONAL") ,expr ,true))
