(defprod element (input ((id string)
			 (label expression)
			 &key (init (init expression))
			 (binding (binding filter))))
  (to-list () `(input (:id ,id :label ,(synth to-list label) :init ,(synth to-list init) :binding ,(synth to-list binding))))
  ;; (to-req (path) (vcat (nest 4 (vcat (if expr (hcat ))
  ;; 				     ))))
  (to-html (path) (div (list :class 'well) 
		       (div nil (text "Campo di input identificato come ~a " (lower id)) 
			    (if (or init label binding) (text "con le seguenti caratteristiche:"))
			    (maybes (list label (span nil (text "Etichetta")))
				    (list init (span nil (text  "Valore iniziale")))
				    (list binding (span nil (text "Data binding"))))))))

