(defprod element (modal ((name symbol)
                         (expr expression)))
  (to-list () `(modal (:name ,name :expr ,(synth to-list expr))))
  (to-html (path) (multitags (text "Finestra modale identificata come ")
                             (span-color (lower-camel name))
                             (text " che visualizza la seguente espressione")
                             (p nil (synth to-html expr))))
  (to-brief (path) (synth to-html (modal name expr) path))
  (to-model () (synth to-model true))
  (toplevel () nil)
  (req (path) (synth req true)))
 
(defmacro modal* (expr)
  `(modal (gensym "MODAL") ,expr))
