(defprod element (panel ((name symbol)
                         (header element)
			 (body element)
			 &optional (footer element)))
  (to-list () `(panel (:name ,name :header ,(synth to-list header) :body ,(synth to-list body) :footer ,(synth to-list footer))))
  ;; (to-req (path) (text "Pannello composto da????????"))
  (to-html (path) (div (list :class 'well) 
		       (div nil 
			    (text "Pannello denominato ~a composto da: " (lower name)) 
			    ;; (description-list (apply #'list (text "header") (text "body") (if footer (text "footer")))
			    ;;     	      (synth-all to-html (apply #'list header body footer) path))
                            (maybes2 (list (list header (span nil (text "header")))
                                           (list body (span nil (text "body")))
                                           (list footer (span nil (text "footer")))) path)))))

(defmacro panel* (header body &optional footer)
  `(panel (gensym "PANEL") ,header ,body ,footer))
