(defprod element (textarea ((name string)
                            (label expression)
                            &key (init (init expression))))
  (to-list () `(textarea (:name ,name :label ,(synth to-list label) :init ,(synth to-list init))))
  (to-html (path) (div (list :class 'well) 
		       (div nil (text "Area di testo identificata come ~a " (lower name)) 
			    (if (or init label) (text "con le seguenti caratteristiche:"))
			    (dlist label (span nil (text "Etichetta")) (synth to-html label)
                                   init (span nil (text "Valore iniziale")) (synth to-html init)))))
  (to-model () (jstring (value (textarea name label :init init)))))

(defmacro textarea* (label &key init)
  `(textarea (gensym "TEXTAREA") ,label :init ,init))
